name: CI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # https://github.com/firecracker-microvm/firecracker/commit/30af4758dafa7eea89ba5ed7071f28e6c1f11f96
  kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display CPU info
        run: lscpu

      - name: Install VM tools
        shell: sudo bash -e {0}
        run: |
          sudo apt-get update
          sudo apt-get install -qq -o=Dpkg::Use-Pty=0 moreutils
          sudo chronic apt-get install -qq -o=Dpkg::Use-Pty=0 vagrant virtualbox qemu libvirt-daemon-system

      - name: Clear additional space on runner
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /var/cache/apt/archives/*
          sudo rm -rf /usr/share/doc/*

          # https://github.com/actions/runner-images/issues/2840
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up VM
        shell: sudo bash -e {0}
        run: |
          vagrant plugin install vagrant-libvirt
          vagrant plugin install vagrant-scp

          vagrant status
          vagrant up --no-tty --provider libvirt

          df -h
          vagrant ssh fbsd -- du -hs /vagrant
      
      - name: Apply src patches
        shell: sudo bash -e {0}
        run: vagrant ssh fbsd -- 'sudo patch -d /usr/src < /vagrant/freebsd-amd-tsc-init.patch'

      - name: Build FreeBSD rootfs and kernel
        shell: sudo bash -e {0}
        run: |
          vagrant ssh fbsd -- sudo /vagrant/build-freebsd.sh
          df -h

      - name: Prepare rootfs
        shell: sudo bash -e {0}
        run: |
          vagrant ssh fbsd -- sudo /vagrant/prepare-rootfs.sh
          df -h

      - name: Copy kernel artifacts
        shell: sudo bash -e {0}
        run: |
          vagrant scp fbsd:/vagrant/freebsd-kern.bin freebsd-kern.bin
          vagrant scp fbsd:/vagrant/freebsd-rootfs.tar.bz2 freebsd-rootfs.tar.bz2

      - name: Archive kernel artifact
        uses: actions/upload-artifact@v3
        with:
          name: freebsd-kern.bin
          path: freebsd-kern.bin
    
      - name: Archive rootfs artifact
        uses: actions/upload-artifact@v3
        with:
          name: freebsd-rootfs.tar.bz2
          path: freebsd-rootfs.tar.bz2
  
  # https://github.com/firecracker-microvm/firecracker/blob/feature/pvh/docs/getting-started.md
  firecracker:
    name: Build Firecracker
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display CPU info
        run: lscpu

      - name: Enable KVM for GHA user
        shell: sudo bash -e {0}
        run: setfacl -m u:${USER}:rw /dev/kvm

      - name: Check KVM support
        run: |
          lsmod | grep kvm
          [ -r /dev/kvm ] && [ -w /dev/kvm ] && echo "OK" || echo "FAIL"
      
      - name: Build Firecracker
        shell: sudo bash -e {0}
        run: |
          git clone --quiet --depth=1 --branch=feature/pvh https://github.com/firecracker-microvm/firecracker
          cd firecracker

          patch -p1 < ../firecracker-mtu-9000.patch

          tools/devtool checkenv

          tools/devtool -y build --release
          mv ./build/cargo_target/$(uname -m)-unknown-linux-musl/release/firecracker firecracker

          ./firecracker --version

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firecracker
          path: firecracker/firecracker
      
  release:
    name: Publish release
    needs: [kernel, firecracker]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04

    steps:
      - name: Download firecracker artifact
        uses: actions/download-artifact@v3
        with:
          name: firecracker
          path: firecracker
      
      - name: Download kernel artifact
        uses: actions/download-artifact@v3
        with:
          name: freebsd-kern.bin
          path: freebsd-kern.bin

      - name: Download rootfs artifact
        uses: actions/download-artifact@v3
        with:
          name: freebsd-rootfs.tar.bz2
          path: freebsd-rootfs.tar.bz2

      - uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.1.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          files: |
            firecracker
            freebsd-kern.bin
            freebsd-rootfs.tar.bz2