name: CI

on:
  push:
    tags:
      - v*
  schedule:
    - cron: '0 6 * * 3'
  workflow_dispatch:

permissions:
  contents: write

env:
  FIRECRACKER_VERSION: "1.12.1"

jobs:
  kernel:
    name: Build Kernel and Rootfs
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display CPU info
        run: lscpu

      - name: Install VM tools
        shell: sudo bash -e {0}
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

          sudo apt-get update
          sudo apt-get install -qq -o=Dpkg::Use-Pty=0 moreutils
          sudo chronic apt-get install -qq -o=Dpkg::Use-Pty=0 vagrant virtualbox qemu-system-x86 libvirt-daemon-system libvirt-dev

      - name: Clear additional space on runner
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /var/cache/apt/archives/*
          sudo rm -rf /usr/share/doc/*

          # https://github.com/actions/runner-images/issues/2840
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up VM
        shell: sudo bash -e {0}
        run: |
          vagrant plugin install vagrant-libvirt
          vagrant plugin install vagrant-scp

          vagrant status
          vagrant up --no-tty --provider libvirt

          df -h
          vagrant ssh fbsd -- du -hs /vagrant

      - name: Build FreeBSD rootfs and kernel
        shell: sudo bash -e {0}
        run: |
          vagrant ssh fbsd -- sudo /vagrant/build-freebsd.sh
          df -h

      - name: Prepare rootfs
        shell: sudo bash -e {0}
        run: |
          vagrant ssh fbsd -- sudo /vagrant/prepare-rootfs.sh
          df -h

      - name: Copy kernel artifacts
        shell: sudo bash -e {0}
        run: |
          vagrant scp fbsd:/vagrant/freebsd-kern.bin freebsd-kern.bin
          vagrant scp fbsd:/vagrant/freebsd-rootfs.bin.xz freebsd-rootfs.bin.xz

      - name: Archive kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: freebsd-kern.bin
          path: freebsd-kern.bin
    
      - name: Archive rootfs artifact
        uses: actions/upload-artifact@v4
        with:
          name: freebsd-rootfs.bin.xz
          path: freebsd-rootfs.bin.xz
  
  firecracker:
    name: Vendor Firecracker binary
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download binary
        run: |
          wget -q -O- https://github.com/firecracker-microvm/firecracker/releases/download/v${{ env.FIRECRACKER_VERSION}}/firecracker-v${{ env.FIRECRACKER_VERSION}}-x86_64.tgz | tar zxf -
          mv release-v${{ env.FIRECRACKER_VERSION}}-x86_64/firecracker-v${{ env.FIRECRACKER_VERSION}}-x86_64 firecracker

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firecracker
          path: firecracker
  
  ssh-keys:
    name: Archive SSH keys
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Archive SSH public key
        uses: actions/upload-artifact@v4
        with:
          name: freebsd.id_rsa.pub
          path: freebsd.id_rsa.pub
        
      - name: Archive SSH private key
        uses: actions/upload-artifact@v4
        with:
          name: freebsd.id_rsa
          path: freebsd.id_rsa

  release:
    name: Publish release
    needs: [firecracker, kernel, ssh-keys]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04

    steps:
      - name: Download firecracker artifact
        uses: actions/download-artifact@v4
        with:
          name: firecracker
          path: firecracker
      
      - name: Download kernel artifact
        uses: actions/download-artifact@v4
        with:
          name: freebsd-kern.bin
          path: freebsd-kern.bin

      - name: Download rootfs artifact
        uses: actions/download-artifact@v4
        with:
          name: freebsd-rootfs.bin.xz
          path: freebsd-rootfs.bin.xz

      - name: Download SSH public key
        uses: actions/download-artifact@v4
        with:
          name: freebsd.id_rsa.pub
          path: freebsd.id_rsa.pub

      - name: Download SSH private key
        uses: actions/download-artifact@v4
        with:
          name: freebsd.id_rsa
          path: freebsd.id_rsa

      - uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.1.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          files: |
            firecracker
            freebsd-kern.bin
            freebsd-rootfs.bin.xz
            freebsd.id_rsa.pub
            freebsd.id_rsa