name: Build FreeBSD Kernel

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display CPU info
        run: lscpu

      - name: Install VM tools
        run: |
          sudo apt-get update
          sudo apt-get install -qq -o=Dpkg::Use-Pty=0 moreutils
          sudo chronic apt-get install -qq -o=Dpkg::Use-Pty=0 vagrant virtualbox qemu libvirt-daemon-system
    
      - name: Set up VM
        shell: sudo bash {0}
        run: |
          vagrant plugin install vagrant-libvirt
          vagrant plugin install vagrant-scp

          vagrant status
          vagrant up --no-tty --provider libvirt
      
      - name: Build kernel
        shell: sudo bash {0}
        run: vagrant ssh fbsd -- bash /vagrant/build-kernel.sh

      - name: Copy kernel artifacts
        run: |
          vagrant scp fbsd:/vagrant/freebsd-kern.bin freebsd-kern.bin
          vagrant scp fbsd:/vagrant/freebsd-rootfs.bin freebsd-rootfs.bin

      - name: Archive kernel artifact
        uses: actions/upload-artifact@v3
        with:
          name: freebsd-kern.bin
          path: freebsd-kern.bin
    
      - name: Archive rootfs artifact
        uses: actions/upload-artifact@v3
        with:
          name: freebsd-rootfs.bin
          path: freebsd-rootfs.bin
